spring:
  datasource:
    #better use schema for keeping data
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      #data-locations: classpath:demo_data.sql
      #for not copying data into the tables comment this string
#here we add some mybatis config using .xml: mybatis maps string to objects
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
    jwt:
     secret: d3FlcXdlZnF3ZWZkc2ZhZHNmZGdsU0RLRkRTRlNGRERTR0ZER1M=
     access: 3600000
     refresh: 2592000000
